

--
-- Please provide parameters marked with <> 
--
--

ALTER SYSTEM SET DB_CREATE_FILE_DEST = '<path for database files>';

CREATE TEMPORARY TABLESPACE "JASPERSERVER_TEMP"
  TEMPFILE 'rptsvc_temp.dbf' SIZE 5M AUTOEXTEND ON;
  
CREATE TABLESPACE "JASPERSERVER" 
	DATAFILE 'rptsvc.dbf' 
	SIZE 102400K 
	REUSE AUTOEXTEND ON 
	NEXT 1024K 
	MAXSIZE 32767M;
	
-- ALTER TABLESPACE "JASPERSERVER" 
--	ADD DATAFILE 'rptsvc.dbf' 
--	SIZE 102400K 
--	REUSE AUTOEXTEND ON 
--	NEXT 1024K 
--	MAXSIZE 32767M;


CREATE DATABASE "JASPERSERVER"
   CONTROLFILE REUSE 
   LOGFILE 'rptsvc.log' SIZE 50K, 
   MAXLOGFILES 5 
   MAXLOGHISTORY 100 
   MAXDATAFILES 10 
   MAXINSTANCES 1 
   ARCHIVELOG 
   CHARACTER SET AL32UTF8
   NATIONAL CHARACTER SET AL16UTF16
   DEFAULT TABLESPACE JASPERSERVER,
   DEFAULT TEMPORARY TABLESPACE JASPERSERVER_TEMP;
	
	
CREATE USER "JASPERSERVER" 
	PROFILE "DEFAULT" 
	IDENTIFIED BY "JASPERSERVER" 
	DEFAULT TABLESPACE "JASPERSERVER" 
	TEMPORARY TABLESPACE "JASPERSERVER_TEMP" 
	ACCOUNT UNLOCK
	GRANT UNLIMITED TABLESPACE TO "JASPERSERVER"
	GRANT "CONNECT" TO "JASPERSERVER"
	GRANT "DBA" TO "JASPERSERVER";


CREATE SCHEMA AUTHORIZATION JASPERSERVER


DROP TABLE "JASPERSERVER"."REPORT_REQUEST_LOG";
DROP TABLE "JASPERSERVER"."ALERT_RESPONSE";
DROP TABLE "JASPERSERVER"."ALERT_RESPONSE_SI";
DROP TABLE "JASPERSERVER"."REPORT_MAP";
DROP TABLE "JASPERSERVER"."REPORT_PARAMETERS_MAP";
DROP SEQUENCE "JASPERSERVER"."REP_REQ_LOG_SEQ";
DROP SEQUENCE "JASPERSERVER"."ALERT_RESPONSE_SEQ";
DROP SEQUENCE "JASPERSERVER"."ALERT_RESPONSE_SI_SEQ";




CREATE TABLE "JASPERSERVER"."REPORT_REQUEST_LOG"
        (
                "ID"                NUMBER(18) NOT NULL,
                "OMGEO_REPORT_ID"   VARCHAR2(40) NOT NULL,
                "SERVICE_REQUESTED" VARCHAR2(20) NOT NULL,
                "REQ_RECD_DATE_TIME" DATE DEFAULT sysdate NOT NULL,
                "REPORT_NAME"   VARCHAR2(20) NOT NULL,
                "ORG_NAME"      VARCHAR2(30),
                "REPORT_TYPE"   VARCHAR2(10),
                "REQUEST_DATA"  VARCHAR2(4000),
                "JASPER_ID"     VARCHAR2(30),
                "JASPER_COOKIE" VARCHAR2(100),
                "ACK_SENT_DATE_TIME" DATE,
                "RESPONSE_DATA" VARCHAR2(2000),
                CONSTRAINT "REPORT_REQUEST_LOG_PK" PRIMARY KEY (ID) 
        );
        
CREATE TABLE "JASPERSERVER"."ALERT_RESPONSE"
        (
                "ID"                    NUMBER(18) NOT NULL,
                "REPORT_REQUEST_LOG_ID" NUMBER(18),
                "ALERT_RESPONSE" CLOB,
                CONSTRAINT "ALERT_RESPONSE_PK" PRIMARY KEY ("ID"),
                CONSTRAINT "ALERT_RESPONSE_FK" FOREIGN KEY ("REPORT_REQUEST_LOG_ID") REFERENCES "JASPERSERVER"."REPORT_REQUEST_LOG" ("ID") ON
        DELETE CASCADE
        );
        
CREATE TABLE "JASPERSERVER"."ALERT_RESPONSE_SI"
        (
                "ID"                NUMBER(18) NOT NULL,
                "ALERT_RESPONSE_ID" NUMBER(18),
                "ALERT_REQ_ID"      VARCHAR2(40) NOT NULL,
                "ALERT_SI_RESPONSE" CLOB,
                CONSTRAINT "ALERT_RESPONSE_SI_PK" PRIMARY KEY ("ID"),
                CONSTRAINT "ALERT_RESPONSE_SI_FK" FOREIGN KEY ("ALERT_RESPONSE_ID") REFERENCES "JASPERSERVER"."ALERT_RESPONSE" ("ID") ON
        DELETE CASCADE
        );
        
CREATE TABLE "JASPERSERVER"."REPORT_MAP"
        (
                "JSON_CALL_NAME"       VARCHAR2(20) NOT NULL,
                "ORG_TYPE"             VARCHAR2(5) NOT NULL,
                "JASPER_REPORT_NAME"   VARCHAR2(50) NOT NULL,
                "REPORT_TYPE"          VARCHAR2(5) NOT NULL ,
                CONSTRAINT "REPORT_MAP_PK" PRIMARY KEY (JSON_CALL_NAME, ORG_TYPE) 
        );
        
CREATE TABLE "JASPERSERVER"."REPORT_PARAMETERS_MAP"
        (
                "JSON_CALL_NAME"           VARCHAR2(20) NOT NULL,
                "ORG_TYPE"                 VARCHAR2(5) NOT NULL,
                "JASPER_PARAMETER"         VARCHAR2(30) NOT NULL,
                "JSON_PARAMETER"           VARCHAR2(20) NOT NULL,
                CONSTRAINT "REPORT_PARAMETERS_MAP_PK" PRIMARY KEY (JSON_CALL_NAME, ORG_TYPE, JASPER_PARAMETER),
                CONSTRAINT FK_REPORT_MAP FOREIGN KEY (JSON_CALL_NAME, ORG_TYPE) REFERENCES "JASPERSERVER".REPORT_MAP(JSON_CALL_NAME, ORG_TYPE) ON
        DELETE CASCADE
        );
        
CREATE SEQUENCE "JASPERSERVER"."REP_REQ_LOG_SEQ" CYCLE ORDER CACHE 20 MAXVALUE 999999999999999999 MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE "JASPERSERVER"."ALERT_RESPONSE_SEQ" CYCLE ORDER CACHE 20 MAXVALUE 999999999999999999 MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE "JASPERSERVER"."ALERT_RESPONSE_SI_SEQ" CYCLE ORDER CACHE 20 MAXVALUE 999999999999999999 MINVALUE 1 INCREMENT BY 1 START WITH 1;


